version: "3"
services:
  hello-backend:
    image: hello-backend
    container_name: hello-backend
    restart: unless-stopped
    volumes:
      - ./public/:/usr/src/app/public
      - ./db/:/usr/src/app/db
    ports:
      - 8090:8090
