version: "3"
services:
  hello-backend:
    image: hello-backend
    container_name: hello-backend
    restart: unless-stopped
    volumes:
      - ./src/public/:/app/public
      - ./src/db/:/app/db
    ports:
      - 8090:8090
